import { build } from "bun";
import { readdirSync, statSync, writeFileSync } from "fs";
import { join, relative } from "path";

// ── Generate examples manifest ────────────────────────────────────────────────

function findTblFiles(dir, base = dir) {
  const results = [];
  for (const entry of readdirSync(dir).sort()) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      results.push(...findTblFiles(full, base));
    } else if (entry.endsWith('.tbl')) {
      // Normalise to forward-slash paths for use in fetch() URLs
      results.push(relative(base, full).replace(/\\/g, '/'));
    }
  }
  return results;
}

const examplesDir = join(import.meta.dir, 'examples');
const examples    = findTblFiles(examplesDir);

writeFileSync(
  join(import.meta.dir, 'examples-manifest.mjs'),
  `// Auto-generated by build.mjs — do not edit\nexport const EXAMPLES = ${JSON.stringify(examples, null, 2)};\n`
);
console.log(`✓ examples-manifest.mjs (${examples.length} examples)`);

// ── Bundle ────────────────────────────────────────────────────────────────────

await build({
  entrypoints: ["./bundle-entry.mjs"],
  outdir: ".",
  naming: "calc.bundle.js",
  target: "browser",
  plugins: [
    {
      name: "node-assert-polyfill",
      setup(build) {
        // Redirect every import of "assert" to a browser-compatible shim,
        // regardless of import style (default, namespace, named).
        build.onResolve({ filter: /^assert$/ }, () => ({
          path: "assert",
          namespace: "assert-polyfill",
        }));
        build.onLoad({ filter: /.*/, namespace: "assert-polyfill" }, () => ({
          contents: `
            export default function assert(cond, msg) {
              if (!cond) throw new Error(msg ?? "Assertion failed");
            }
          `,
          loader: "js",
        }));
      },
    },
  ],
});

console.log("✓ calc.bundle.js written");
